# Location of oh-myzsh
export ZSH=$HOME/.oh-my-zsh

# My own variation of theme "amuse"
ZSH_THEME="my-agnoster"

# Plugins
plugins=(git)

# Dunno lol
source $ZSH/oh-my-zsh.sh

# Enable powerline
#powerline-daemon -q
#. /usr/lib/python3.8/site-packages/powerline/bindings/zsh/powerline.zsh

# Banner
neofetch --crop_mode normal -- size 350px --kitty ~/Pictures/Greets/minimal_ghibli.jpg



