# Location of oh-myzsh
export ZSH=$HOME/.oh-my-zsh

# My own variation of theme "amuse"
ZSH_THEME="my-agnoster"

# gpg-agent for ssh
export SSH_AGENT_PID=""
export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh"
export GPG_TTY=$(tty)

# fix ssh in kitty terminal
[ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"

# Plugins
plugins=(git)

# Dunno lol
source $ZSH/oh-my-zsh.sh

# Enable powerline
#powerline-daemon -q
#. /usr/lib/python3.8/site-packages/powerline/bindings/zsh/powerline.zsh

# Banner
neofetch
